/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PdfDocument {
  pages(): PdfPages;
}

export declare class PdfPage {
  text(): string;
  render(
    width: number,
    height: number,
    rotation?: Rotation | undefined | null
  ): Uint8ClampedArray | null;
}

export declare class PdfPages {
  len(): number;
  get(index: number): PdfPage | null;
}

export declare class PdfViewer {
  constructor();
  static bindToLibrary(path: string): PdfViewer;
  openWithId(id: string): PdfDocument | null;
  open(
    id: string,
    bytes: Buffer,
    password?: string | undefined | null
  ): PdfDocument | null;
  close(id: string): boolean;
}

export declare const enum Rotation {
  Zero = 0,
  One = 1,
  Two = 2,
  Three = 3,
}
